theme: jekyll-theme-Modernist
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Name - Portfolio</title>
    <link rel="stylesheet" href="styles.css"> <!-- Link to your CSS file for styling -->
</head>
<body>

    <!-- Header Section -->
    <header>
        <h1>Your Name</h1>
        <p>Web Developer</p>
    </header>

    <!-- Navigation Section -->
    <nav>
        <ul>
            <li><a href="#about">About Me</a></li>
            <li><a href="#projects">Projects</a></li>
            <li><a href="#skills">Skills</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>

    <!-- About Me Section -->
    <section id="about">
        <h2>About Me</h2>
        <p>Write a brief introduction about yourself, your background, and your interests.</p>
    </section>

    <!-- Projects Section -->
    <section id="projects">
        <h2>Projects</h2>
        <!-- List your projects with brief descriptions and links to GitHub or live demos -->
        <div class="project">
            <h3>Project 1</h3>
            <p>Description of Project 1.</p>
            <a href="link-to-project-1">GitHub</a>
        </div>
        <!-- Repeat the structure for other projects -->
    </section>

    <!-- Skills Section -->
    <section id="skills">
        <h2>Skills</h2>
        <!-- List your skills, e.g., programming languages, frameworks, tools -->
        <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>JavaScript</li>
            <!-- Add more skills -->
        </ul>
    </section>

    <!-- Contact Section -->
    <section id="contact">
        <h2>Contact</h2>
        <p>Provide contact information or a contact form for visitors to reach out to you.</p>
    </section>

    <!-- Footer Section -->
    <footer>
        <p>&copy; 2023 Your Name. All rights reserved.</p>
    </footer>

</body>
</html>
